@startuml

object Module {
  Kernelモジュールや、EnumerableモジュールはModuleクラスのオブジェクト(インスタンス)
}

object Class{
  StringクラスやArrayクラスはClassクラスのオブジェクト(インスタンス)
}

object Object {
}

Object <|-- Module
Module <|-- Class

@enduml
