# 使用するRubyのバージョンを指定する
AllCops:
  TargetRubyVersion: 2.3

# コメントに日本語を使用できるようにする
Style/AsciiComments:
  Enabled: false

# ダブルクォートでエラーがでないようにする
StringLiterals:
  EnforcedStyle: double_quotes

# beginがdef全域に及ぶ場合でもエラーがでないようにする
# RedundantBegin: false
