@startuml

object Human {
  ①
}

object モジュールB {
  ②
}

object モジュールA {
  ③
}

object Mammals {
  ④
}

object Object {
  ⑤
}

object Kernel {
  ⑥
}

object BasicObject {
  ⑦
}

Human .r.|> モジュールB:include
Human .r.|> モジュールA:include
Mammals <|-- Human
Object <|-- Mammals
Object .r.|> Kernel:include
BasicObject <|-- Object

@enduml
